repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
    # - id: check-added-large-files
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 24.2.0
  - hooks:
      - id: pyupgrade
    repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
  - hooks:
      - id: upgrade-type-hints
    repo: https://github.com/sondrelg/pep585-upgrade
    rev: v1.0
  - hooks:
      - id: blacken-docs
    repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
  - hooks:
      - args:
          - --target-version
          - "3.2"
        id: django-upgrade
    repo: https://github.com/adamchainz/django-upgrade
    rev: 1.16.0
  - hooks:
      - id: djhtml
    repo: https://github.com/rtts/djhtml
    rev: 3.0.6
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.14.1
