repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
    # - id: check-added-large-files
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 22.1.0
  - hooks:
      - id: pyupgrade
    repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
  - hooks:
      - id: upgrade-type-hints
    repo: https://github.com/sondrelg/pep585-upgrade
    rev: v1
  - hooks:
      - additional_dependencies:
          - black==21.12b0
        id: blacken-docs
    repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
  - hooks:
      - args:
          - --target-version
          - "3.2"
        id: django-upgrade
    repo: https://github.com/adamchainz/django-upgrade
    rev: 1.4.0
  - hooks:
      - id: djhtml
    repo: https://github.com/rtts/djhtml
    rev: v1.5.0
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.21.2
